### ISSUE TITLE
raise ValueError('Please provide the owner of the repository.') as part of Github Actions execution

### ISSUE THREAD

**Issue by dj-wasabi** [dj-wasabi/dj-wasabi-release#44]
Error while `release.py -d` is executed on a different repository as part of an Github Action.

```
Traceback (most recent call last):
  File "/home/runner/work/pre-commit-hooks/pre-commit-hooks/main/../dj-wasabi-release/release.py", line 194, in <module>
    main()
  File "/home/runner/work/pre-commit-hooks/pre-commit-hooks/main/../dj-wasabi-release/release.py", line 133, in main
    githubUrl = djWasabi.generic.getGithubUrl(owner=owner, repository=repository)
  File "/home/runner/work/pre-commit-hooks/pre-commit-hooks/dj-wasabi-release/lib/djWasabi/generic.py", line 144, in getGithubUrl
Error:     raise ValueError('Please provide the owner of the repository.')
ValueError: Please provide the owner of the repository.
Error: Process completed with exit code 1.
```

**Comment by dj-wasabi** [comment]
Is fixed now.
